<link rel="stylesheet" href="http://192.168.0.53:8080/arcgis_js_api/library/3.4/3.4/js/dojo/dijit/themes/tundra/tundra.css"> 
<link rel="stylesheet" href="http://192.168.0.53:8080/arcgis_js_api/library/3.4/3.4/js/dojo/dijit/themes/claro/claro.css">
<link rel="stylesheet" href="http://192.168.0.53:8080/arcgis_js_api/library/3.4/3.4/js/esri/css/esri.css">
<script type="text/javascript">djConfig = { parseOnLoad:true }</script>
<script type="text/javascript" src="http://192.168.0.53:8080/arcgis_js_api/library/3.4/3.4/init.js"></script>
<script type="text/javascript" src="gis/gis.js"></script>
<script type="text/javascript" src="gis/drawSection.js" charset="UTF-8"></script>
<script type="text/javascript" src="gis/gisLayer.js"></script>
